"""Canonical platform-independent models shared across the BSFAI core."""

from .device import (
    CommandExecutionResult,
    CommandExecutionStatus,
    DeviceCapabilities,
    DeviceProfile,
)
from .inventory import (
    BatteryPackIdentity,
    BindingState,
    DeviceBindingProposal,
    DeviceControlState,
    DeviceInventory,
    DiscoveryCandidate,
    MainDevice,
    NativeDeviceIdentity,
    ZendureTransport,
)
from .market import (
    MarketPrice,
    MarketPriceDirection,
    MarketPriceForecast,
    MarketPricePoint,
    MarketPriceValidity,
)
from .regulation import (
    AutomaticStrategyResult,
    ChargeSourceAllocation,
    DeviceCommand,
    GridHistoryState,
    ModeArbiterResult,
    PowerControllerResult,
    RegulationRuntimeState,
    StrategyContext,
    StrategyIntent,
)
from .runtime import AiMode, DecisionContext, RuntimeSnapshot
from .states import (
    AdditionalBatteryState,
    BatteryState,
    GridState,
    MeasuredValue,
    OffGridState,
    PVState,
    ValueValidity,
)
from .strategy import (
    ChargeCommitState,
    StrategicState,
    StrategyDecision,
    VisibleState,
)

__all__ = [
    "AdditionalBatteryState",
    "AiMode",
    "AutomaticStrategyResult",
    "BatteryState",
    "BatteryPackIdentity",
    "BindingState",
    "ChargeCommitState",
    "ChargeSourceAllocation",
    "CommandExecutionResult",
    "CommandExecutionStatus",
    "DeviceCapabilities",
    "DeviceBindingProposal",
    "DeviceControlState",
    "DeviceInventory",
    "DeviceProfile",
    "DeviceCommand",
    "DecisionContext",
    "GridHistoryState",
    "GridState",
    "DiscoveryCandidate",
    "MarketPrice",
    "MarketPriceDirection",
    "MarketPriceForecast",
    "MarketPricePoint",
    "MarketPriceValidity",
    "MeasuredValue",
    "MainDevice",
    "ModeArbiterResult",
    "NativeDeviceIdentity",
    "OffGridState",
    "PVState",
    "PowerControllerResult",
    "RegulationRuntimeState",
    "RuntimeSnapshot",
    "StrategicState",
    "StrategyContext",
    "StrategyDecision",
    "StrategyIntent",
    "ValueValidity",
    "VisibleState",
    "ZendureTransport",
]
